name: Dispatch CI

on:
  # At 11:55 AM UTC, only on Tuesday and Wednesday
  schedule:
    - cron: '55 11 * * 2,3'

jobs:
  dispatch-ci:
    name: Dispatch CI
    # Only run cron on the silverstripe account
    if: (github.event_name == 'schedule' && github.repository_owner == 'silverstripe') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch CI
        uses: silverstripe/gha-dispatch-ci@v1
